name: KitPvP
main: com.github.caaarlowsz.kakashimc.kitpvp.Main
author: Kakashi
description: Plugin de KitPvP Para o Servidor ...
version: 1.0
commands:
  fly:
  report:
  status:
  rank:
  xp:
  score:
  kit:
  resetkit:
  gm:
  ajuda:
  gamemode:
  build:
  admin:
  congelar:
  pvp:
  tag:
  warp:
  warpset:
  aviso:
  cc:
  kills:
  clicktest:
  fake:
  tell:
  chat:
  set:
  uncage:
  aplicar:
  sendmsg:
  sc:
  caixa:
  setarena:
  darkit:
  tp:
  tphere:
  tpall:
  vis:
  spawn:
  head:
  youtuber:
